server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

